# Jekyll configuration

name: CivBuddy
description: Helper app for Francis Tresham's &quot;Civilization&quot; board game

# enable emoticons
plugins:
  - jemoji

# website address
url: https://civbuddy.org

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'tsjensen/civbuddy'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''


permalink: /:year/:month/:title
#paginate: 10
future: true

markdown: kramdown
kramdown:
  input: GFM

exclude: ['README.md', 'LICENSE', '*.iml', 'build', 'out', 'node_modules']
